### ISSUE TITLE
Neutral language in specifications

### ISSUE THREAD

**Issue by deniak** [w3c/manual-of-style#7]
Add a paragraph to discourage the use of terms like:
* master/slave
* whitelist/blacklist
* grandfather*
* sanity
* dummy
* he/she
* him/her

Here are some possible alternatives respectively:
* leader/follower or primary/standby
* allowlist/denylist
* legacy status
* coherence
* placeholder/sample

/cc @koalie

**Comment by koalie** [comment]
I think "main/replica" would be a more appropriate replacement for our anticipated usage of "master/slave".
Thanks!

**Comment by sidvishnoi** [comment]
It might be helpful to get list of such terms from https://github.com/retextjs/retext-equality.
